version: '3'

services:

  jobify-app:
    image: node:18
    container_name: jobify-jenkins-container
    working_dir: /app
    volumes:
      - ./:/app                               # Mount repo root (backend + other files)
      - ./Client/Jobify/dist:/app/Client/Jobify/dist  # Mount frontend build explicitly
    command: sh -c "node server.js"
    ports:
      - "8082:5000"   # Host 8082 â†’ container 5000
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/jobify
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-for-jenkins
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
