version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: jobify-mongo-2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    image: zeenia1997/jobify-full:v1
    container_name: jobify-app-2
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/jobify
      PORT: 5000
    ports:
      - "8082:5000"

volumes:
  mongo_data:
